Repository amundsen-io/amundsenfrontendlibrary, pull requests merged in 2020-02, with the labels that each got.

#382 use schemas for metadata retrieval & update search field names
  amundsen_application/api/metadata/v0.py
  amundsen_application/api/search/v0.py
  amundsen_application/api/utils/metadata_utils.py
  amundsen_application/models/user.py
  amundsen_application/static/js/components/TableDetail/ColumnListItem/index.tsx
  amundsen_application/static/js/components/TableDetail/ColumnListItem/tests/index.spec.tsx
  amundsen_application/static/js/components/TableDetail/DataPreviewButton/index.tsx
  amundsen_application/static/js/components/TableDetail/ExploreButton/index.tsx
  amundsen_application/static/js/components/TableDetail/FrequentUsers/index.tsx
  amundsen_application/static/js/components/TableDetail/LineageLink/index.tsx
  amundsen_application/static/js/components/TableDetail/RequestMetadataForm/index.tsx
  amundsen_application/static/js/components/TableDetail/RequestMetadataForm/tests/index.spec.tsx
  amundsen_application/static/js/components/TableDetail/TableDescEditableText/index.tsx
  amundsen_application/static/js/components/TableDetail/index.tsx
  amundsen_application/static/js/components/common/Bookmark/MyBookmarks/tests/index.spec.tsx
  amundsen_application/static/js/components/common/ResourceListItem/TableListItem/index.tsx
  amundsen_application/static/js/components/common/ResourceListItem/TableListItem/tests/index.spec.tsx
  amundsen_application/static/js/components/common/SearchBar/InlineSearchResults/index.tsx
  amundsen_application/static/js/components/common/SearchBar/InlineSearchResults/tests/index.spec.tsx
  amundsen_application/static/js/ducks/bookmark/tests/index.spec.ts
  amundsen_application/static/js/ducks/search/tests/index.spec.ts
  amundsen_application/static/js/ducks/tableMetadata/api/helpers.ts
  amundsen_application/static/js/ducks/tableMetadata/api/tests/index.spec.ts
  amundsen_application/static/js/ducks/tableMetadata/api/v0.ts
  amundsen_application/static/js/ducks/tableMetadata/reducer.ts
  amundsen_application/static/js/fixtures/globalState.ts
  amundsen_application/static/js/fixtures/search/inlineResults.ts
  amundsen_application/static/js/interfaces/Resources.ts
  amundsen_application/static/js/interfaces/TableMetadata.ts
  requirements.txt
  setup.py
  tests/unit/api/metadata/test_v0.py
  tests/unit/api/search/test_v0.py
Labels: 2.0.0, keep fresh

#387 Update node-sass to fix security issue
  amundsen_application/static/package-lock.json
  amundsen_application/static/package.json
Labels: stale

#386 Added last_updated_timestamp to table details page
  amundsen_application/static/js/components/Footer/index.tsx
  amundsen_application/static/js/components/Footer/tests/index.spec.tsx
  amundsen_application/static/js/components/TableDetail/ColumnStats/index.tsx
  amundsen_application/static/js/components/TableDetail/ColumnStats/tests/index.spec.tsx
  amundsen_application/static/js/components/TableDetail/WatermarkLabel/constants.ts
  amundsen_application/static/js/components/TableDetail/WatermarkLabel/index.tsx
  amundsen_application/static/js/components/TableDetail/index.tsx
  amundsen_application/static/js/components/common/ResourceListItem/TableListItem/index.tsx
  amundsen_application/static/js/components/common/ResourceListItem/TableListItem/tests/index.spec.tsx
  amundsen_application/static/js/config/config-default.ts
  amundsen_application/static/js/config/config-types.ts
  amundsen_application/static/js/ducks/search/sagas.ts
  amundsen_application/static/js/ducks/search/tests/index.spec.ts
  amundsen_application/static/js/ducks/tableMetadata/reducer.ts
  amundsen_application/static/js/fixtures/globalState.ts
  amundsen_application/static/js/index.tsx
  amundsen_application/static/js/interfaces/TableMetadata.ts
  amundsen_application/static/js/utils/dateUtils.ts
  amundsen_application/static/js/utils/navigationUtils.ts
  amundsen_application/static/js/utils/tests/index.spec.ts
  docs/application_config.md
  tests/unit/api/metadata/test_v0.py
Labels: 2.1.0
