Repository amundsen-io/amundsenfrontendlibrary, pull requests merged in 2020-01, with the labels that each got.

#362 Implements the functionality to customize the logging - Same as Metadata Service
  amundsen_application/__init__.py
  amundsen_application/config.py
  setup.py
Labels: 1.2.1

#368 Upgrade node version
  .travis.yml
  README.md
  amundsen_application/static/package-lock.json
  amundsen_application/static/package.json
  amundsen_application/static/tslint.json
  amundsen_application/static/webpack.common.ts
Labels: 1.2.1

#361 Filter UX Improvements
  amundsen_application/api/search/v0.py
  amundsen_application/static/jest.config.js
  amundsen_application/static/js/components/SearchPage/SearchFilter/CheckBoxFilter/index.tsx
  amundsen_application/static/js/components/SearchPage/SearchFilter/FilterSection/index.tsx
  amundsen_application/static/js/components/SearchPage/SearchFilter/InputFilter/index.tsx
  amundsen_application/static/js/components/SearchPage/SearchFilter/constants.ts
  amundsen_application/static/js/components/SearchPage/SearchFilter/index.tsx
  amundsen_application/static/js/components/SearchPage/SearchFilter/styles.scss
  amundsen_application/static/js/components/SearchPage/SearchFilter/tests/index.spec.tsx
  amundsen_application/static/js/components/SearchPage/constants.ts
  amundsen_application/static/js/components/SearchPage/index.tsx
  amundsen_application/static/js/components/SearchPage/tests/index.spec.tsx
  amundsen_application/static/js/ducks/rootSaga.ts
  amundsen_application/static/js/ducks/search/api/v0.ts
  amundsen_application/static/js/ducks/search/filters/reducer.ts
  amundsen_application/static/js/ducks/search/reducer.ts
  amundsen_application/static/js/ducks/search/sagas.ts
  amundsen_application/static/js/ducks/search/tests/index.spec.ts
  amundsen_application/static/js/fixtures/search/filters.ts
  amundsen_application/static/js/interfaces/Filters.ts
  amundsen_application/static/js/interfaces/index.ts
  amundsen_application/static/js/utils/navigation-utils.ts
Labels: keep fresh

#357 Initial Filter React/Redux Modifications
  amundsen_application/api/search/v0.py
  amundsen_application/api/utils/request_utils.py
  amundsen_application/static/jest.config.js
  amundsen_application/static/js/components/SearchPage/SearchFilter/CheckBoxFilter/index.tsx
  amundsen_application/static/js/components/SearchPage/SearchFilter/FilterSection/index.tsx
  amundsen_application/static/js/components/SearchPage/SearchFilter/InputFilter/index.tsx
  amundsen_application/static/js/components/SearchPage/SearchFilter/constants.ts
  amundsen_application/static/js/components/SearchPage/SearchFilter/index.tsx
  amundsen_application/static/js/components/SearchPage/SearchFilter/styles.scss
  amundsen_application/static/js/components/SearchPage/SearchFilter/tests/index.spec.tsx
  amundsen_application/static/js/components/SearchPage/SearchPanel/styles.scss
  amundsen_application/static/js/components/SearchPage/constants.ts
  amundsen_application/static/js/components/SearchPage/index.tsx
  amundsen_application/static/js/components/SearchPage/tests/index.spec.tsx
  amundsen_application/static/js/components/common/Inputs/CheckBoxItem/index.tsx
  amundsen_application/static/js/components/common/Inputs/styles.scss
  amundsen_application/static/js/components/common/SearchBar/constants.ts
  amundsen_application/static/js/components/common/SearchBar/index.tsx
  amundsen_application/static/js/components/common/SearchBar/tests/index.spec.tsx
  amundsen_application/static/js/config/config-default.ts
  amundsen_application/static/js/config/config-types.ts
  amundsen_application/static/js/config/config-utils.ts
  amundsen_application/static/js/config/tests/index.spec.ts
  amundsen_application/static/js/ducks/rootSaga.ts
  amundsen_application/static/js/ducks/search/api/v0.ts
  amundsen_application/static/js/ducks/search/filters/reducer.ts
  amundsen_application/static/js/ducks/search/reducer.ts
  amundsen_application/static/js/ducks/search/sagas.ts
  amundsen_application/static/js/ducks/search/tests/index.spec.ts
  amundsen_application/static/js/fixtures/globalState.ts
  amundsen_application/static/js/fixtures/search/filters.ts
  amundsen_application/static/js/interfaces/Enums.ts
  amundsen_application/static/js/interfaces/Resources.ts
  amundsen_application/static/js/utils/navigation-utils.ts
Labels: keep fresh

#363 Amundsen Notifications functionality improvements
  amundsen_application/api/mail/v0.py
  amundsen_application/api/utils/notification_utils.py
  amundsen_application/base/base_mail_client.py
  amundsen_application/base/examples/example_mail_client.py
  amundsen_application/static/js/components/TableDetail/index.tsx
  amundsen_application/static/js/config/config-types.ts
  tests/unit/utils/notification/test_utils.py
Labels: 1.2.1, keep fresh
